// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oqaobnkcgfdqkxvaltki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xYW9ibmtjZ2ZkcWt4dmFsdGtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1OTQwOTYsImV4cCI6MjA2MTE3MDA5Nn0.TjtZI3o16MGii0CNAZumUYzEXSYZAGot3d8lxX8gHYE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);